### ISSUE TITLE
How to generate collision.obj files?

### ISSUE THREAD

**Issue by laynewong** [ChenEating716/pybullet-URDF-models#2]
Hi,
I'd like to know how to generate collision.obj files for YCB models or my own models(any textured.obj). I can't seem to find a way to do this. Can you tell me how you did it? Thank you.

**Comment by ChenEating716** [comment]
Hi,
please refer to:
https://arxiv.org/pdf/1502.03143.pdf
https://arxiv.org/pdf/2104.11446.pdf
